= Prerequisites for MuleSoft Accelerator for Financial Services

This page provides a summary of the guides available for configuring the various systems and products required to implement the use cases provided by this solution. The individual systems needed, and amount of configuration required, depend on which assets are to be deployed in your target environment(s) - refer to the use case pages for more details.

== Available Guides

The following setup and configuration guides are available for this accelerator:

* xref:anypointmq-setup-guide.adoc[Anypoint MQ setup guide]
* xref:payments-setup-guide.adoc[Payments modernization demo setup guide]
* xref:rpa-setup-guide.adoc[RPA Setup Guide]
* xref:sfdc-data-cloud-setup-guide.adoc[Salesforce Data Cloud setup guide]
* xref:sfdc-fsc-setup-guide.adoc[Salesforce Financial Services Cloud setup guide]
* xref:sfdc-mc-setup-guide.adoc[Salesforce Marketing Cloud setup guide]

Most of the implementation templates also contain details on requirements specific to those applications.

== See Also

* xref:accelerators-home::getting-started.adoc[Getting Started Guide]
* xref:index.adoc[MuleSoft Accelerator for Financial Services]
