= Getting started with MuleSoft Accelerators

This guide will help you configure your local build environment to ensure success in downloading, modifying, and deploying accelerator assets.

== Quick Start

To get started, you must set up your local build environment with the required software and Maven build configuration. Next, download and configure the assets required for the use case(s) you wish to implement. Some use cases will require changes to the systems being integrated (e.g., SAP, Salesforce Service Cloud, and so on) - be sure to read and follow the instructions specified for each accelerator carefully. This also applies when using only a few select assets instead of implementing complete use cases.

Once configured, applications can be deployed individually to your own CloudHub instance, either manually or by using simple Maven commands. There may also be some helper configuration files available for deploying multiple components at once. The following instructions assume you have already configured your Maven `settings.xml` file according to the xref:accel-build-environment.adoc[Build environment configuration] guide.

=== Asset Types

The following table provides more information about the types of accelerator assets provided and how they fit into the overall solution.

[%header%autowidth.spread]
|===
|Type	|Purpose	|Example
|API Spec Fragments	|Shared RAML specifications reused by multiple APIs. These define standard characteristics, data types and response codes common across most APIs.	|Accelerator Global Resources
|REST APIs	|RAML specifications describing the resources and methods an API makes available to consumers. They are categorized into layers - System, Process, Experience - as per MuleSoft's API-led approach.	|Accelerator OMS System API
|Templates	|Runtime implementations of individual APIs and other integrations. These must be customized and deployed to your own Mule runtime environment (e.g., CloudHub) to implement desired use cases.	|Accelerator OMS System API - Implementation Template
|Custom	assets |Documentation and other downloadable components that do not fit into other categories.	|Accelerator POM Parent - Source
|===

=== Obtaining accelerator assets

All accelerator assets are available from the main Anypoint Exchange site and are freely downloadable by customers with current subscriptions. Refer to the sections in the page navigation menu on the left for more information about configuring, building, and deploying these assets.

==== Import Directly from Anypoint Exchange

All accelerator templates can be imported into Anypoint Studio directly from Exchange if your Anypoint credentials have been provided; refer to the Studio documentation for more details.

* From Studio, open the Exchange window (typically the second toolbar button from the left)
* If prompted, login to Anypoint Exchange
* Select the `Provided by MuleSoft` view (top-left)
* Click the `Asset type` selector to the left of the `Search` field and choose `Templates`
* Copy and paste the title of this API into the `Search` field and press `Enter`
* Click on the desired result to open the home page for the asset
* Click on the `Open` icon (top-right) to import the asset into the current workspace

If it appears, you can safely cancel out of the `Update your Workspace` dialog as well as the subsequent `Are you sure?` prompt: our templates will work correctly with or without the suggested changes.

==== Download and Import Manually

The following instructions assume you are viewing this page from your browser:

* Click the `Download` button (top-right) and save the template archive to your local file system
* In Studio, ensure the current perspective is set to `Mule Design`
* Right-click in an empty area in the `Package Explorer` and select `+Import...+`
* In the select dialog, expand the `Anypoint Studio` folder
* Choose the `Packaged mule application (.jar)` option and click `Next >`
* Enter the full path name of the downloaded jar file or select from the file browser
* Remove the version and `mule-application-template` suffixes from the project name, if desired
* Click `Finish` to import the project

As above, you can safely cancel out of the `Update your Workspace` dialog, if prompted.

=== Next Steps

Ensure your xref:accel-build-environment.adoc[Build Environment] is configured correctly before attempting to import or deploy any assets. Also refer to the xref:accel-application-deployment.adoc[Application Deployment], xref:accel-application-testing.adoc[Application Testing] and xref:accel-additional-customizations.adoc[Additional Customizations] pages for more details on deploying, testing, and customizing accelerator assets.

== See Also

* xref:accel/accel-build-environment.adoc[Build environment]
* xref:accel/accel-application-deployment.adoc[Application deployment]
* xref:accel/accel-application-testing.adoc[Application testing]
* xref:accel/accel-additional-customizations.adoc[Additional customizations]
* xref:index.adoc[MuleSoft Accelerators]
