= MuleSoft Accelerators Setup Guide

This guide will help you configure your local build environment to ensure success in downloading, modifying, and deploying accelerator assets.

== Quick Start

To get started, you must set up your local build environment with the required software and Maven build configuration. Next, download and configure the assets required for the use case(s) you wish to implement. Some use cases will require changes to the systems being integrated (e.g., SAP, Salesforce Service Cloud, and so on) - be sure to read and follow the instructions specified for each accelerator carefully. This also applies when using only a few select assets instead of implementing complete use cases.

Once configured, applications can be deployed individually to your own CloudHub instance, either manually or by using simple Maven commands. There may also be some helper configuration files available for deploying multiple components at once.

== Next Steps

Ensure your xref:accel-build-environment.adoc[Build Environment] is configured correctly before attempting to import or deploy any assets. Also refer to the xref:accel-application-deployment.adoc[Application Deployment], xref:accel-application-testing.adoc[Application Testing] and xref:accel-additional-customizations.adoc[Additional Customizations] pages for more details on deploying, testing, and customizing accelerator assets.

== Asset Types

The following table provides more information about the types of accelerator assets provided and how they fit into the overall solution.

[%header%autowidth.spread]
|===
|Type	|Purpose	|Example
|API Spec Fragments	|Shared RAML specifications reused by multiple APIs. These define standard characteristics, data types and response codes common across most APIs.	|Accelerator Global Resources
|REST APIs	|RAML specifications describing the resources and methods an API makes available to consumers. They are categorized into layers - System, Process, Experience - as per MuleSoft's API-led approach.	|Accelerator OMS System API
|Templates	|Runtime implementations of individual APIs and other integrations. These must be customized and deployed to your own Mule runtime environment (e.g., CloudHub) to implement desired use cases.	|Accelerator OMS System API - Implementation Template
|Custom	assets |Documentation and other downloadable components that do not fit into other categories.	|Accelerator POM Parent - Source
|===

== Obtaining accelerator assets

All accelerator assets are available from the main Anypoint Exchange site and are freely downloadable by customers with current subscriptions. Refer to the sections in the page navigation menu on the left for more information about configuring, building, and deploying these assets.

== See Also

* The xref:index.adoc[MuleSoft Accelerators] main page.
