= MuleSoft Accelerator for Manufacturing

Seamless connectivity between core systems like SAP S/4HANA, Product Information Management (PIM) systems, Salesforce Manufacturing Cloud, and Salesforce Rebate Management with pre-built APIs, integration templates, reference architectures, and connectors.

Transparency is key to eliminating waste and managing costs in a manufacturing environment. Manufacturing companies have the data to make critical decisions, but are inhibited from making timely decisions due to siloed and disconnected data.

MuleSoft Accelerator for Manufacturing equips discrete and process manufacturers with foundational assets for common use cases to accelerate their digital transformation journey. Our pre-built APIs, implementation templates, reference architecture, and connectors allow IT teams to spend more time innovating, and less time building common integrations from scratch.

== Use Cases

* https://anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-manufacturing/minor/1.1/pages/Use%20case%201%20-%20Run-rate%20business%20management/[Use case 1 - Run-rate business management] — Syncing data from SAP S/4HANA and PIM systems into Manufacturing Cloud can be challenging and time consuming. This solution seamlessly sends customer and order data from SAP into Manufacturing Cloud. It also sends product data and price lists from a PIM system into Salesforce Manufacturing Cloud. As a result, it enables sales teams to have a complete view of customer sales agreements.Visibility into sales agreements provides predictability, which is critical to manage any manufacturing business. This precision in predictability helps manufacturers and their customers with their run-rate business:

* https://anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-manufacturing/minor/1.1/pages/Use%20case%202%20-%20Sales%20rebate%20management/[Use case 2 - Sales rebate management] — Manually uploading sales rebate payout details from Salesforce Rebate Management to SAP can be error prone. This solution seamlessly syncs customer and sales order data between SAP and Salesforce Manufacturing Cloud, and creates a credit memo in SAP in line with program guidelines and calculations. As a result, sales teams can trust that aggregate customer sales order data will trigger the correct sales rebate payouts and accounting teams will benefit from seamless documentation and tracking of sales rebate payments.Manufacturing companies can reliably trust unified data to make informed rebate management decisions to drive future growth.

=== Shared Use Cases (located in the MuleSoft Accelerator for SAP):

* Procure-to-pay — Streamline your procure-to-pay process with pre-built APIs, implementation templates, and connectors to seamlessly move supplier, invoice, and goods receipt data.
* Quote-to-cash: Salesforce and SAP S/4HANA — Sync order, inventory, and customer data from opportunity to close between Salesforce Sales Cloud (including CPQ) and SAP S/4HANA.
* Quote-to-cash: B2B EDI — Enable the sales order/purchase order and post-purchase order transaction flows between businesses, with one business serving as the buyer and the other as the supplier. This is to support the inclusion of EDI message formats (both X12 and EDIFACT formats) as a form of communication between applications. You can also easily integrate Slack with sales and purchase orders for prompt action by the operation and service teams.
* Real-time and bulk data lakes integration — Send sales order, inventory, and customer information from source systems to common data lake storage repositories. This integration creates a foundation for surfacing key objects in a structured data warehouse and ultimately an analytics platform like Tableau for predictive business intelligence.

== Available Assets

=== System APIs

MFG Salesforce Customers System API
MFG Salesforce Manufacture System API
MFG Salesforce Orders System API
MFG Salesforce Products System API
MFG SAP S/4HANA Customers System API
MFG SAP S/4HANA Orders System API
Manufacturing MDM System API
PIM System API
MFG Salesforce Rebate System API
MFG SAP S/4HANA Credit Memo System API

=== Process APIs

MFG Bulk Load Process API
MFG Customers Process API
MFG Orders Process API
MFG Products Process API
PIM Sync Process API
MFG Rebate Process API

=== Experience APIs

MFG Bulk Load Experience API
MFG Salesforce Experience API

==== Accelerator Listeners

MFG SAP Event Listener
MFG Salesforce Topic Listener

=== Custom components

Accelerator Common Core
POM Parent
ID Graph Lightning Web Component
MFG Rebate Library
Common Services (can be used across any use case)

== See Also

* xref:accelerators::getting-started.adoc[Getting Started Guide]
* xref:prerequisites.adoc[Prerequisites]
* xref:release-notes.adoc[Release Notes]
