= Prerequisites

== Service Accounts

Service accounts are needed for the applications below, with the versions used during Accelerator development noted:

* Salesforce B2C Commerce (Version 20.6, Compatibility Mode 19.10)
* Salesforce Marketing Cloud (April 2021)
* Salesforce (Spring '21)
* SAP (ECC 7.5)

Additional resources used:

* Global Data Management System (GDM) - MySQL 8.x used as GDM
* Order Management System (OMS) - Apache OFBiz used as OMS
* Product Information Management (PIM) - Oracle 11g used as PIM

== Required Configuration

In addition to configuring individual applications to suit your target deployment environment, the following will be required to implement the use cases described:

* B2C Commerce Configuration: Open Commerce and Salesforce Commerce API access in addition to deployment and configuration of the B2C Commerce Sync Cartridge.
* Salesforce Configuration: Addition of custom fields and enabling Person Accounts (details can be found https://help.salesforce.com/articleView?id=000328922&type=1&mode=1[here]) in addition to creating a push topic on Account object with appropriate filters.
* Salesforce Marketing Cloud: A custom Data Extension will need to be created along with an Installed Package to make API requests.
* SAP Configuration: Deployment of the custom SAP BAPI code required.

== Optional Configuration

The accelerator includes some additional common components, which can be configured to suit your needs. These are all optional:

* Configurable properties in the common core library
* Notification APIs for sending error notifications via email, SMS or Slack
* Common scheduler for executing jobs on a schedule

Please refer to the https://anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-salesforce-common-services/[Accelerators Common Services] documentation for more details on configuring optional components.

== See Also 

* xref:index.adoc[MuleSoft Accelerator for Retail]
