= Prerequisites for MuleSoft Accelerator for Retail

This page provides a summary of the guides available for configuring the various systems and products required to implement the use cases provided by this solution. The individual systems needed, and amount of configuration required, depend on which assets are to be deployed in your target environment(s) - refer to the use case pages for more details.

== Available Guides

The following setup and configuration guides are available for this accelerator:

* xref:rcg-setup-guide.adoc[Accelerator Setup Guide]
* xref:b2c-setup-guide.adoc[B2C Setup Guide]
* xref:ofbiz-setup-config.adoc[OFBiz Setup and Configuration]
* xref:sap-s4hana-setup-guide.adoc[SAP S4HANA Setup Guide]
* xref:sap-custom-bapi-setup-guide.adoc[SAP Custom BAPI Setup Guide]
* xref:salesforce-customization-guide.adoc[Salesforce Customization Guide]
* xref:salesforce-cdp-setup-guide.adoc[Salesforce CDP Setup Guide]

Most of the implementation templates also contain details on requirements specific to those applications.

== See Also

* xref:accelerators-home::getting-started.adoc[Getting Started Guide]
* xref:index.adoc[MuleSoft Accelerator for Retail]
