<<<<<<< HEAD:modules/ROOT/pages/retail/rcg-setup-guide.adoc
= Accelerator Setup Guide

This page provides guidance on configuring the various systems and products required to implement the use cases provided by this solution.

== Service Accounts

Service accounts are needed for the applications below, with the versions used during Accelerator development noted:

* Salesforce B2C Commerce (Version 20.6, Compatibility Mode 19.10)
* Salesforce Marketing Cloud (April 2021)
* Salesforce (Spring '21)
* SAP (ECC 7.5)

Additional resources used:

* Global Data Management System (GDM) - MariaDB used as GDM
* Order Management System (OMS) - Apache OFBiz used as OMS
* Product Information Management (PIM) - Oracle 11g used as PIM

== Required Configuration

=======
<<<<<<<< HEAD:modules/ROOT/pages/retail/retail-prereqs.adoc
= Prerequisites for MuleSoft Accelerator for Retail
========
= Accelerator Setup Guide

This page provides guidance on configuring the various systems and products required to implement the use cases provided by this solution.
>>>>>>>> 97bb809 (Squashing unverified commits from the beta branch):retail/2.7/modules/ROOT/pages/rcg-setup-guide.adoc

This page provides a summary of the guides available for configuring the various systems and products required to implement the use cases provided by this solution. The individual systems needed, and amount of configuration required, depend on which assets are to be deployed in your target environment(s) - refer to the use case pages for more details.

== Available Guides

The following setup and configuration guides are available for this accelerator:

* xref:rcg-setup-guide.adoc[Accelerator Setup Guide]
* xref:b2c-setup-guide.adoc[B2C Setup Guide]
* xref:ofbiz-setup-config.adoc[OFBiz Setup and Configuration]
* xref:sap-s4hana-setup-guide.adoc[SAP S4HANA Setup Guide]
* xref:sap-custom-bapi-setup-guide.adoc[SAP Custom BAPI Setup Guide]
* xref:sfdc-customization-guide.adoc[Salesforce Customization Guide]
* xref:sfdc-data-cloud-setup-guide.adoc[Salesforce Data Cloud Setup Guide]

<<<<<<<< HEAD:modules/ROOT/pages/retail/retail-prereqs.adoc
Most of the implementation templates also contain details on requirements specific to those applications.
========
* Global Data Management System (GDM) - MariaDB used as GDM
* Order Management System (OMS) - Apache OFBiz used as OMS
* Product Information Management (PIM) - Oracle 11g used as PIM
>>>>>>>> 97bb809 (Squashing unverified commits from the beta branch):retail/2.7/modules/ROOT/pages/rcg-setup-guide.adoc

== See Also

<<<<<<<< HEAD:modules/ROOT/pages/retail/retail-prereqs.adoc
* xref:accelerators-home::getting-started.adoc[Getting Started Guide]
========
>>>>>>> 97bb809 (Squashing unverified commits from the beta branch):retail/2.7/modules/ROOT/pages/rcg-setup-guide.adoc
In addition to configuring individual applications to suit your target deployment environment, the following will be required to implement the use cases described:

* B2C Commerce Configuration: Open Commerce and Salesforce Commerce API access in addition to deployment and configuration of the B2C Commerce Sync Cartridge.
* Salesforce Configuration: Addition of custom fields and enabling Person Accounts (details can be found https://help.salesforce.com/articleView?id=000328922&type=1&mode=1[here]) in addition to creating a push topic on Account object with appropriate filters.
* Salesforce Marketing Cloud: A custom Data Extension will need to be created along with an Installed Package to make API requests.
* SAP Configuration: Deployment of the custom SAP BAPI code required.

== Optional Configuration

The accelerator includes some additional common components, which can be configured to suit your needs. These are all optional:

* Configurable properties in the common core library
* Notification APIs for sending error notifications via email, SMS or Slack
* Common scheduler for executing jobs on a schedule

Please refer to the xref:accelerators-home::common-services.adoc[Accelerators Common Services] documentation for more details on configuring optional components.

== See Also 

* xref:prerequisites.adoc[Prerequisites]
<<<<<<< HEAD:modules/ROOT/pages/retail/rcg-setup-guide.adoc
=======
>>>>>>>> 97bb809 (Squashing unverified commits from the beta branch):retail/2.7/modules/ROOT/pages/rcg-setup-guide.adoc
>>>>>>> 97bb809 (Squashing unverified commits from the beta branch):retail/2.7/modules/ROOT/pages/rcg-setup-guide.adoc
* xref:index.adoc[MuleSoft Accelerator for Retail]
