= Release Notes
:retail-version: 2.7

== v2.7

15 September 2022

=== Updates to Existing Retail Use Cases

This release includes updates to all the assets in the Accelerator for Retail to use the latest versions of the following common services:

* https://www.anypoint.mulesoft.com/exchange/org.mule.examples/accelerator-pom-parent-src/minor/{retail-version}/[Accelerator POM Parent : 2.3.1^]
* https://www.anypoint.mulesoft.com/exchange/org.mule.examples/accelerator-common-core-src/minor/{retail-version}/[Accelerator Common Core : 2.3.2^]

== v2.6

31 May 2022

=== Updates to the Product Sync Use Case

This release includes the updates to https://www.anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-retail/minor/{retail-version}/pages/Use%20case%203%20-%20Product%20sync/[Product sync^] use case, which synchronizes and unifies product updates from Salsify and SAP S/4HANA across relevant applications, with one application serving as the primary definition of the product.

== v2.5

26 April 2022

=== New Use Case

This release includes the https://www.anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-retail/minor/{retail-version}/pages/Use%20case%205%20-%20Deliver%20relevancy%20with%20CDP/[Deliver relevancy with CDP^] use case, which synchronizes and unifies customer profile data into a customer data platform so that you can personalize interactions by customer segment.

== v2.4

25 January 2022

=== New Use Case

This release includes the https://www.anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-retail/minor/{retail-version}/pages/Use%20case%204%20-%20Real-time%20inventory%20management/[Real-time inventory management^] use case, which enables customers to make an informed decision of their online purchase based on real-time inventory of a product in nearby stores.

== v2.3

23 November 2021

Made the following improvements in this release:

* Enhanced product sync to support product variations as described https://documentation.b2c.commercecloud.salesforce.com/DOC1/index.jsp?topic=%2Fcom.demandware.dochelp%2Fcontent%2Fb2c_commerce%2Ftopics%2Fproducts%2Fb2c_product_variations.html[here^].

== v2.2.1

21 September 2021

=== New use case

This release includes the https://www.anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-retail/minor/{retail-version}/pages/Use%20case%203%20-%20Product%20sync/[Product sync^] use case, which enables the creation and updates of products across relevant applications, with one application serving as the primary definition of the product.

== v2.2

29 July 2021

Made the following improvements in this release:

* Enhanced customer sync to support Organizations
* Retrofitted all System APIs to reflect the following:
** Renamed "master" query parameters in API specs
** Renamed "master" custom fields in back-end systems
* Revised object structure on published B2C Commerce orders
* Made additional bug fixes and additional enhancements

== v2.1

6 July 2021

=== New Use Case

This release includes the https://www.anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-retail/minor/{retail-version}/pages/Use%20case%202%20-%20Sales%20order%20sync/[Sales order sync^] use case, which enables retail developers to calculate the total lifetime value of a customer by unlocking order data from disparate systems.

== v2.0

10 May 2021

=== Initial release

This is the first release of the MuleSoft Accelerator for Retail. It has been released as version 2.0 due to the inclusion of some shared assets, which had previously been released with other Accelerators.

This accelerator also introduces the https://www.anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-retail/minor/{retail-version}/pages/Use%20case%201%20-%20Customer%20profile%20sync/[Customer profile sync^] use case (and four extension use cases), which enables retail developers to create a customer 360 view by unlocking customer data from disparate systems.

== See Also 

* xref:index.adoc[MuleSoft Accelerator for Retail]
