= Release Notes

== v1.5
July 15, 2022

=== Client Onboarding - Wealth Management Use Case

This use case enables a streamlined and automated client onboarding solution. Wealth management client service teams will be able to reduce the risk of manual errors by integrating systems and digitizing workflows

== v1.4
April 28, 2022

=== Address Change Orchestration Use Case

Introduces the Address change orchestration use case. There are two extensions of this use case:

* xref:fins/fins-use-case-address-change-banking.adoc[Use case 4a - Address change orchestration: Insurance] — Streamline downstream events that result from policyholder or carrier postal address adjustments. The address change orchestration use case for insurance delivers a solution for address confirmation, seamless policyholder data updates, and single home policy coverage assessments, resulting in faster policyholder premium updates.
* xref:fins/fins-use-case-address-change-ins.adoc[Use case 4b - Address change orchestration: Banking] — Enhance your customer service teams’ upsell, cross-sell, and service opportunities that result from customer postal code address changes. The address change orchestration use case for banking supports faster address validation and increased customer service opportunities, including personalized products and offers.

== v1.3
March 21, 2022

=== Minor Updates

A few assets were updated to correct minor issues, including:

* Database creation scripts
* Visualizer layer assignments
* Documentation updates

January 28, 2022

=== Payments Modernization Use Case

Introduces the Payments modernization use case, which accelerates the development of modern payment solutions for Financial Institutions. Banks and Credit Unions will be able to deliver a diverse payments landscape that can address multiple types of financial transactions and customer needs.

== v1.2
November 16, 2021

=== Core Banking Enhancements

This release includes the following enhancements:

* Added more information to both the customer accounts sync and customer onboarding use cases
* Added credit card functionality
* Added full two-way synchronization capabilities between customer accounts, transactions, and credit cards

See the Upgrade notes for more information.

== v1.1
September 9, 2021

=== Customer Onboarding Use Case

Introduces the Customer onboarding - Banking use case, which allows leverages Salesforce Financial Services Cloud as the system of engagement, DocuSign as the document management system, and Equifax as the credit analysis system.

== v1.0
July 27, 2021

=== Initial Release

This is the first release of the MuleSoft Accelerator for Financial Services.

This accelerator also introduces the Core banking foundation use case, which allows for the display of a customer’s financial summary from multiple systems. The customer and customer service representative (CSR) views are supported in this release.

== See Also

* xref:fins-upgrade-notes.adoc[Upgrade Notes]
* xref:fins-landing-page.adoc[MuleSoft Accelerator for Financial Services]
