= MuleSoft Accelerator for Financial Services

MuleSoft Accelerator for Financial services simplifies customer 360 initiatives by unlocking both core banking and insurance platforms, systems of engagement (such as CRM and ITSM), Insuretechs, and FinTech data. This enables a higher level of customer service, real-time relationship management, and a more connected digital experience.

== Use Cases

=== Core Banking Foundation

The https://www.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-financial-services/minor/1.6/pages/Use%20case%201%20-%20Core%20banking%20foundation/[Core Banking Foundation^] use case allows for the display of a customer’s financial summary from multiple systems. The solution supports a customer service view and a customer service representative view.

=== Onboarding

Accelerates the delivery and development of an enhanced onboarding solution to streamline banking loan origination and wealth management client account opening procedures. There are two extensions for this use case:

* https://www.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-financial-services/minor/1.6/pages/Use%20case%202a%20-%20Customer%20onboarding%20-%20Banking/[Customer Onboarding - Banking^]

* https://www.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-financial-services/minor/1.6/pages/Use%20case%202b%20-%20Client%20onboarding%20-%20Wealth%20management/[Client Onboarding - Wealth management^]

=== Payments Modernization

The https://www.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-financial-services/minor/1.6/pages/Use%20case%203%20-%20Payments%20modernization/[Payments Modernization use case^] accelerates the development of modern payment solutions for Financial Institutions. Banks and Credit Unions will be able to deliver a diverse payments landscape that can address multiple types of financial transactions and customer needs.

=== Address Change Orchestration

Accelerates the delivery and development of a home address validation solution for streamlining downstream processes impacted by postal address changes. There are two extensions for this use case:

* https://www.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-financial-services/minor/1.5/pages/Use%20case%204a%20-%20Address%20change%20orchestration%20-%20Insurance/[Address Change Orchestration: Insurance^]

* https://www.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-financial-services/minor/1.5/pages/Use%20case%204b%20-%20Address%20change%20orchestration%20-%20Banking/[Address Change Orchestration: Banking^]

== Available Assets

Accelerator assets include API specifications, implementation templates, custom assets, and common services. Most interfaces use canonical data model definitions, which makes these assets plug and play and highly reusable. Individual assets can therefore be leveraged either as part of a use case, following the reference architecture provided, or independently to support different use cases, depending on your needs.

=== FINS System APIs

include::partial$fins-system-apis-fragment.adoc[]

=== FINS Process APIs

include::partial$fins-process-apis-fragment.adoc[]

=== FINS Experience APIs

include::partial$fins-experience-apis-fragment.adoc[]

=== FINS Listeners

include::partial$fins-listeners-fragment.adoc[]

=== FINS Custom Components

include::partial$fins-custom-components-fragment.adoc[]

=== Shared Accelerator Assets

A number of shared assets and common services are also used by this accelerator.

==== Accelerator System APIs

[%hardbreaks]
xref:../accel/system-apis/accelerator-email-system-api.adoc[Accelerator Email System API]
xref:../accel/system-apis/accelerator-slack-system-api.adoc[Accelerator Slack System API]
xref:../accel/system-apis/accelerator-sms-system-api.adoc[Accelerator SMS System API]

==== Accelerator Process APIs

[%hardbreaks]
xref:../accel/process-apis/accelerator-notifications-process-api.adoc[Accelerator Notifications Process API]

==== Accelerator Custom Components

[%hardbreaks]
xref:../accel/api-libraries/accelerator-cim-global-library.adoc[Accelerator CIM Global Library]
xref:../accel/api-libraries/accelerator-cim-market-library.adoc[Accelerator CIM Market Library]
xref:../accel/api-libraries/accelerator-cim-fins-library.adoc[Accelerator CIM FINS Extension Library]
xref:../accel/shared-components/accelerator-common-core.adoc[Accelerator Common Core]
xref:../accel/shared-components/accelerator-idgraph-lwc.adoc[Accelerator ID Graph Lightning Web Component]
xref:../accel/shared-components/accelerator-knit-maven-plugin.adoc[Accelerator Knit Maven Plugin]
xref:../accel/shared-components/accelerator-pom-parent.adoc[Accelerator POM Parent]

== See Also

* Required xref:./fins-prerequisites.adoc[Prerequisites] for this accelerator
* https://www.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-financial-services/[MuleSoft Accelerator for Financial Services^] on Anypoint Exchange
* Documentation home page for xref:../index.adoc[MuleSoft Accelerators]
