= Upgrade Notes

This page provides some basic information for those upgrading to newer releases of the MuleSoft Accelerator for Financial Services.

== Release 1.7 to Release 1.8

As mentioned in the release notes, a number of technical and architectural changes introduced in this release will have an impact on existing deployments. These impacts, and the corresponding upgrade considerations, should be addressed in the following order as appropriate for your deployments:

- Create platform event and triggers in Salesforce, deploy Accelerators Salesforce Party Listener and Accelerators Salesforce Financial Account Event Listener.

- Replace FINS Customer Process API with the Accelerator Customer Process API.

- A large number of other assets, which have not been included in the asset list for this release, have also been published to reflect changes in dependencies on both API specifications and other applications.

== Release 1.6 to Release 1.7

As mentioned in the release notes, a number of technical and architectural changes introduced in this release will have an impact on existing deployments. These impacts, and corresponding upgrade considerations, should be addressed in the following order as appropriate for your deployments.

- If changes have been made to the data types in the FINS Common, Banking, or Insurance RAML libraries, it is recommended that you deploy the new CIM libraries to your local environment and reflect the same changes there for use by the updated API specs.

- While the new applications may work correctly against a MySQL database, it is recommended that you provision a new MariaDB instance and start with a fresh schema. The data structures have largely stayed the same, so it should be possible to transfer existing data (via export/import) from the old DB to the new one, if desired. However, new constraints have been introduced, which may prevent some existing data from being loaded successfully.

- After deploying the new Global Data Management APIs and other applications referenced by this use case you should undeploy the original MDM System APIs to ensure they are no longer being referenced. Depending on your environment you may also need to redeploy the latest versions of the following applications: Bank Loans Process API, Customer Addresses Process API, Mobile Experience API, Salesforce Financial Experience API, and Salesforce Insurance Experience API.

- Since the new Jack Henry SilverLake and Synergy System APIs, along with the Events Experience API, replace the original generic Core Banking database implementations, the following applications can be undeployed: Core Banking Poller Process API, Core Banking Accounts System API, and Core Banking Customers System API.

- A large number of other assets, which have not been included in the asset lists for this release, have also been published to reflect changes in dependencies on both API specifications and other applications. It is therefore highly recommended that you upgrade all existing deployements to the latest versions found on Exchange to ensure compatibility with older use cases.

=== Core Banking Limitations

It is important to note that the Jack Henry SilverLake provider does not include support for all of the functionality that was originally implemented by the generic Core Banking System APIs. This may cause exisiting test cases and demo scripts to fail under certain conditions - please consult the documentation for the SilverLake System APIs for more details.

== Release 1.5 to Release 1.6

There were no breaking changes introduced by this release. The existing Salesforce Customers System API was enhanced to support the posting of messages to chatter feeds; all other APIs included in this release were net new.

== Release 1.4 to Release 1.5

The following changes introduced in this release may impact existing deployments:

* The publishing of updates to customer profiles (including individuals and organizations) has been streamlined to use only one set of Anypoint MQ destinations for parties and another set for party roles. Upgrading will require the new destinations to be created before redeploying any affected assets.
* The DocuSign Experience and System APIs have been refactored to make them more generic. Assets related to the processing of Loan Applications have been updated accordingly and will need to be redeployed. This includes the Bank Loans Process API and the Loan Origination System API.

== Release 1.3 to Release 1.4

The existing customer sync process was augmented yet again to support the Postal Address Change use case, which will have an impact on existing deployments of these components. There is also a new, cleaner version of the CIM Market library included in this release.

=== Change Summary

The following changes may have an impact on existing deployments:

* The CIM libraries were upgraded to new versions containing better examples and simplified (but more complete) JSON schemas.
* The Notifications Process API is now referenced as a shared service.
* Support for additional Salesforce FSC record types has been added.
* The ID Graph LWC has been updated.

=== Upgrade Steps

If a release earlier than 1.3, incorporate the previous upgrade steps into the following ones.

. Apply the latest configuration changes to your Salesforce Financial Services Cloud instance as documented in the customization guide.
. Deploy the latest ID Graph LWC asset to your target Salesforce org(s).
. Apply the latest schema changes to the Core Banking and MDM databases.
** This may require some updates to existing records.
. Deploy the latest customer sync components included in this release.

=== Verification Steps

* Create a new customer in Salesforce FSC, ensure it is replicated to Core Banking and MDM.
* Update the same customer in FSC, ensure the update is reflected in Core Banking and MDM.
* Ensure the Customer ID Graph component displays all target systems correctly.
* Repeat these tests for financial accounts, transactions, and cards in FSC.
* Repeat the above steps for customers, accounts, transactions, and cards in Core Banking.
* Walk through the Loan Origination scenario and ensure customer and loan account are properly created in FSC, Core Banking, and MDM.

== Release 1.2 to Release 1.3

In addition to new components introduced for the Payments Modernization use case, this release also includes updates to existing Core Banking, MDM, and Salesforce integration components.

=== Change Summary

The following changes may have an impact on existing deployments:

* Objects in the Banking Library and associated database schemas have been expanded.
* Additional support for Organization parties in the customer sync process was introduced.
* Select properties in a number of objects have been made read-only once created.
* Support for storing multiple external identifiers in the generic Core Banking System has been removed.
* Anypoint Studio has been upgraded to 7.11 along with a number of connectors, modules, and plugins.

=== Upgrade Steps

If a release earlier than 1.2, incorporate the previous upgrade steps into the following ones.

. Apply the latest schema changes to the Core Banking and MDM databases.
** This may require some updates to existing records.
. Upgrade local Anypoint Studio instance to 7.11.
** Create a new workspace for importing assets from this release.
. Deploy the latest customer sync components included in this release.

=== Verification Steps

* Create a new customer in Salesforce FSC, ensure it is replicated to Core Banking and MDM.
* Update the same customer in FSC, ensure the update is reflected in Core Banking and MDM.
* Repeat these tests for financial accounts, transactions, and cards in FSC.
* Repeat the above steps for customers, accounts, transactions, and cards in Core Banking.

== Upgrading earlier releases to Release 1.2

This release introduced some significant changes from earlier releases. As a result, all assets from both use cases have been republished to ensure proper interaction between the components.

=== Change Summary

The following changes may have an impact on existing deployments:

* FIS integration has been replaced with a generic database-backed Core Banking System.
* A generic database-backed Credit Card System has been added.
* MDM functions have been refactored into separate APIs for Customers and Financial Accounts.
* New versions of the Salesforce Lightning Web Components used by the solution have been incorporated.
* Salesforce Financial Services Cloud requires additional customization and configuration steps.
* Full two-way synchronization of customer and financial account information has been introduced.

=== Upgrade Steps

The following steps should be performed when upgrading existing installations to this release:

. Apply the latest configuration changes to your Salesforce Financial Services Cloud instance as documented in the customization guide.
. Redeploy the new versions of the LWC components.
. Create a new database schema for the Core Banking System.
. Apply the schema creation scripts found in the two Core Banking System API implementation projects.
. Create a new database schema for the Credit Card System.
. Apply the schema creation script found in the Credit Card System API implementation project.
. Undeploy the existing MDM and FIS System APIs.
. Execute the `Anypoint-MQ-Configuration` Postman collection in the `fins-common-resources` project to create required MQ destinations.
. Deploy/redeploy all implementation assets required for both use cases.

=== Verification Steps

The following tests can be done to ensure proper deployment of all components for the core banking foundation and customer onboarding use cases:

* Create a new customer in Salesforce FSC, ensure it is replicated to Core Banking and MDM.
* Update the same customer in FSC, ensure the update is reflected in Core Banking and MDM.
* Repeat these tests for financial accounts, transactions, and cards in FSC.
* Repeat the above steps for customers, accounts, transactions, and cards in Core Banking.
* Walk through the Loan Origination scenario and ensure customer and loan account are properly created in FSC, Core Banking, and MDM.

== See Also

<<<<<<<< HEAD:financial-services/1.9/modules/ROOT/pages/upgrade-notes.adoc
* xref:index.adoc[MuleSoft Accelerator for Financial Services]
========
* xref:fins-landing-page.adoc[MuleSoft Accelerator for Financial Services]
>>>>>>>> 1148e9a (Update common-services.adoc):modules/ROOT/pages/fins/fins-upgrade-notes.adoc
