= Upgrade Notes

This page provides some basic information for those upgrading to newer releases of the MuleSoft Accelerator for Financial Services.

== Upgrading from Release 1.5 to Release 1.6

There were no breaking changes introduced by this release. The existing Salesforce Customers System API was enhanced to support the posting of messages to chatter feeds; all other APIs included in this release were net new.

== Upgrading from Release 1.4 to Release 1.5

The following changes introduced in this release may impact existing deployments:

* The publishing of updates to customer profiles (including individuals and organizations) has been streamlined to use only one set of Anypoint MQ destinations for parties and another set for party roles. Upgrading will require the new destinations to be created before redeploying any affected assets.
* The DocuSign Experience and System APIs have been refactored to make them more generic. Assets related to the processing of Loan Applications have been updated accordingly and will need to be redeployed. This includes the Bank Loans Process API and the Loan Origination System API.

== Upgrading from Release 1.3 to Release 1.4

The existing customer sync process was augmented yet again to support the Postal Address Change use case, which will have an impact on existing deployments of these components. There is also a new, cleaner version of the CIM Market library included in this release.

=== Change Summary

The following changes may have an impact on existing deployments:

* The CIM libraries were upgraded to new versions containing better examples and simplified (but more complete) JSON schemas.
* The Notifications Process API is now referenced as a shared service.
* Support for additional Salesforce FSC record types has been added.
* The ID Graph LWC has been updated.

=== Upgrade Steps

If upgrading from a release earlier than 1.3, incorporate the previous upgrade steps into the following ones.

. Apply the latest configuration changes to your Salesforce Financial Services Cloud instance as documented in the customization guide.
. Deploy the latest ID Graph LWC asset to your target Salesforce org(s).
. Apply the latest schema changes to the Core Banking and MDM databases.
** This may require some updates to existing records.
. Deploy the latest customer sync components included in this release.

=== Verification Steps

* Create a new customer in Salesforce FSC, ensure it is replicated to Core Banking and MDM.
* Update the same customer in FSC, ensure the update is reflected in Core Banking and MDM.
* Ensure the Customer ID Graph component displays all target systems correctly.
* Repeat these tests for financial accounts, transactions, and cards in FSC.
* Repeat the above steps for customers, accounts, transactions, and cards in Core Banking.
* Walk through the Loan Origination scenario and ensure customer and loan account are properly created in FSC, Core Banking, and MDM.

== Upgrading from Release 1.2 to Release 1.3

In addition to new components introduced for the Payments Modernization use case, this release also includes updates to existing Core Banking, MDM, and Salesforce integration components.

=== Change Summary

The following changes may have an impact on existing deployments:

* Objects in the Banking Library and associated database schemas have been expanded.
* Additional support for Organization parties in the customer sync process was introduced.
* Select properties in a number of objects have been made read-only once created.
* Support for storing multiple external identifiers in the generic Core Banking System has been removed.
* Anypoint Studio has been upgraded to 7.11 along with a number of connectors, modules, and plugins.

=== Upgrade Steps

If upgrading from a release earlier than 1.2, incorporate the previous upgrade steps into the following ones.

. Apply the latest schema changes to the Core Banking and MDM databases.
** This may require some updates to existing records.
. Upgrade local Anypoint Studio instance to 7.11.
** Create a new workspace for importing assets from this release.
. Deploy the latest customer sync components included in this release.

=== Verification Steps

* Create a new customer in Salesforce FSC, ensure it is replicated to Core Banking and MDM.
* Update the same customer in FSC, ensure the update is reflected in Core Banking and MDM.
* Repeat these tests for financial accounts, transactions, and cards in FSC.
* Repeat the above steps for customers, accounts, transactions, and cards in Core Banking.

== Upgrading earlier releases to Release 1.2

This release introduced some significant changes from earlier releases. As a result, all assets from both use cases have been republished to ensure proper interaction between the components.

=== Change Summary

The following changes may have an impact on existing deployments:

* FIS integration has been replaced with a generic database-backed Core Banking System.
* A generic database-backed Credit Card System has been added.
* MDM functions have been refactored into separate APIs for Customers and Financial Accounts.
* New versions of the Salesforce Lightning Web Components used by the solution have been incorporated.
* Salesforce Financial Services Cloud requires additional customization and configuration steps.
* Full two-way synchronization of customer and financial account information has been introduced.

=== Upgrade Steps

The following steps should be performed when upgrading existing installations to this release:

. Apply the latest configuration changes to your Salesforce Financial Services Cloud instance as documented in the customization guide.
. Redeploy the new versions of the LWC components.
. Create a new database schema for the Core Banking System.
. Apply the schema creation scripts found in the two Core Banking System API implementation projects.
. Create a new database schema for the Credit Card System.
. Apply the schema creation script found in the Credit Card System API implementation project.
. Undeploy the existing MDM and FIS System APIs.
. Execute the Anypoint-MQ-Configuration Postman collection in the fins-common-resources project to create required MQ destinations.
. Deploy/redeploy all implementation assets required for both use cases.

=== Verification Steps

The following tests can be done to ensure proper deployment of all components for the core banking foundation and customer onboarding use cases:

* Create a new customer in Salesforce FSC, ensure it is replicated to Core Banking and MDM.
* Update the same customer in FSC, ensure the update is reflected in Core Banking and MDM.
* Repeat these tests for financial accounts, transactions, and cards in FSC.
* Repeat the above steps for customers, accounts, transactions, and cards in Core Banking.
* Walk through the Loan Origination scenario and ensure customer and loan account are properly created in FSC, Core Banking, and MDM.

== See Also

* xref:./fins-landing-page.adoc[MuleSoft Accelerator for Financial Services]
