= Release Notes
:mfg-version: 1.4

== v1.4

*October 23, 2023*

The Run-rate Business Management use case is updated to remove the dependency on MDM and optimize it for direct integration between ERP and CRM systems, such as connecting SAP S/4HANA data to Salesforce Manufacturing Cloud. As part of this update, the use case name is changed to https://anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-manufacturing/minor/{mfg-version}/pages/Use%20case%201%20-%20Account%20and%20product%20and%20order%20sync/[Account and product and order sync^].

== v1.2

6 September 2022

=== Total Productive Maintenance Use Case

This release introduces the https://anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-manufacturing/minor/{mfg-version}/pages/Use%20case%203%20-%20Total%20productive%20maintenance/[Total productive maintenance^] use case, which helps manufacturers to maintain factory floor equipments.

== v1.1

8 June 2022

=== Sales Rebate Management Use Case

This release introduces the https://anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-manufacturing/minor/{mfg-version}/pages/Use%20case%202%20-%20Sales%20rebate%20management/[Sales rebate management^] use case, which helps manufacturers to seamlessly manage sales rebate programs.

This release also includes the following enhancements:

* customers can be synced bidirectionally between SAP S/4 HANA and Salesforce Manufacturing Cloud.

== v1.0

28 March 2022

=== Initial Release

This is the first release of the MuleSoft Accelerator for Manufacturing.

This release introduces the https://anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-manufacturing/minor/{mfg-version}/pages/Use%20case%201%20-%20Run-rate%20business%20management/[Run-rate business management^] use case, which helps streamline sales agreements and account forecasts in Salesforce Manufacturing Cloud.

== See Also

* xref:index.adoc[MuleSoft Accelerator for Manufacturing]
