= Use Case - Client Onboarding - Wealth Management
Streamline and accelerate the onboarding experience for your clients and financial advisors

Overview
The wealth management industry continues to face increasing pressure to modernize client experiences and adopt new technologies. Wealth management firms need to respond to increasing digital consumer demands to remain competitive and relevant. Automating the onboarding process results in a secure, streamlined experience, resulting in less manual errors and greater compliance.

This use case accelerates IT team’s ability to deliver an enhanced onboarding experience built on a foundation of automation. Organizations can expect reduced onboarding time, greater efficiency, and improved client and financial advisor experiences.

Use case description
The client onboarding solution integrates and connects data between Salesforce Financial Services Cloud, Marketing Cloud, Slack, and DocuSign. Financial Services Cloud acts as the engagement layer to manage the onboarding process. Marketing Cloud supports client communication. Slack is leveraged for internal communication and notifications. DocuSign supports document generation during the onboarding process.

Note: Underlying systems and endpoints can be further customized based on your organizations needs. Please speak with your account team for more information.

Glossary
Term	Definition
CIM	The Cloud Information Model for MuleSoft Accelerators defines a set of standard data structures that can be used as canonical representations of common entities for integrating systems.
FINS	Abbreviated term referring to the Financial and Insurance industries, consisting of the Banking, Insurance, and Wealth Management domains.
FSC	The Salesforce Financial Services Cloud suite of applications. This includes Retail Banking, basic Insurance capabilities, and Wealth & Asset Management.
MDM	A Master Data Management (MDM) solution provides an accurate, consistent, and complete copy of master data for use by enterprise applications and business partners. Most solutions include data quality tools and workflow processes for managing conflicting updates.
WAM	Wealth & Asset Management is a sub-vertical of FINS.
Before you begin
bulb.png	The Accelerators set up guide provides general information on getting started with the accelerator components. This includes instructions on setting up your local workstation for configuring and deploying the applications.
API-led diagram
API-led diagram for WAM client onboarding
Solution overview
The goal of this solution is to add support for onboarding new WAM clients onto Salesforce FSC via a marketing campaign.

The solution supports the following functionality:

Ability to create leads in Salesforce FSC when a potential client responds to a marketing campaign
Automatic Know Your Client (KYC) checks when leads become opportunities
Automatic document generation when opportunities pass KYC
Update of opportunities based on the results of KYC checks
Support for synchronizing household accounts between Salesforce FSC instances
High-level architecture
The following diagram represents the portion of the solution that pertains to the client onboarding for wealth management use case.

Architecture diagram for WAM client onboarding
Technical considerations and constraints
The following lists the technical considerations and constraints for this solution design:

Salesforce FSC Wealth will be the system of record for Wealth & Asset Management
The system will not convert leads into opportunities: this must be done by the Financial Advisor
The KYC check will be simulated in this release; it can be replaced with a system API that runs the KYC check with a suitable backend
Processing views
This section provides detailed processing sequences for lead, opportunity, and document notification handling.

Lead creation
A potential client responds to a marketing campaign by submitting a form. The system takes the information and creates a new Lead in FSC Wealth for review by a financial advisor. Please follow instructions outlined in the Marketing Cloud setup guide for setting up the email campaign.

The creation of a lead begins with a request from Marketing Cloud to the Salesforce Wealth Experience API.

Activity diagram for lead creation
Opportunity processing
A Lead is reviewed and converted to an Opportunity in FSC by the financial advisor if they determine that the lead is a good candidate for a potential client.

The opportunity creation triggers a KYC check. If the check passes, onboarding documents are generated and sent out for signature.

The processing of a new opportunity begins with an update event posted to Anypoint MQ by the Salesforce Topic Listener.

Activity diagram for opportunity processing
Document notification
DocuSign sends a notification that the client has signed the forms, and the opportunity is marked as closed/won in FSC Wealth.

This activity begins with DocuSign invoking the DocuSign Experience API via a configured webhook to notify that the documents are signed and the onboarding process can be completed.

Activity diagram for document notification
Household synchronization
The synchronization of Household accounts (an Account object with a record type of Household) begins with an update event being received by the Salesforce Topic Listener from one of the Salesforce FSC orgs. While the diagram below shows the update originating from Wealth, the process is the same for Banking and Insurance as well.

Note: This process is depicted as using "upserts" for persisting objects in FSC solely for the purpose of keeping the diagram readable. In actual fact, the system APIs have separate endpoints for the creation and update of objects to allow for a wider range of use cases. The logic to look up an object to determine whether a create or update call is required is part of the Customers Process API - it is just not shown here for the sake of clarity.

Activity diagram for household synchronization
Downloadable assets
FINS System APIs

Accelerator Slack System API | API Specification | Implementation Template
DocuSign System API | API Specification | Implementation Template
MDM Customers System API | API Specification | Implementation Template
Salesforce Customers System API | API Specification | Implementation Template
Salesforce Financial System API | API Specification | Implementation Template
FINS Process APIs

Customer Leads Process API | API Specification | Implementation Template
Customers Process API | API Specification | Implementation Template
FINS Experience APIs

DocuSign Experience API | API Specification | Implementation Template
Salesforce Wealth Experience API | API Specification | Implementation Template
FINS Listeners

Salesforce Topic Listener | Implementation Template
Custom components

Accelerator CIM Global Library | Source
Accelerator CIM Market Library | Source
Accelerator Common Core | Source
Accelerator POM Parent | Source
FINS Common Library | Source
FINS Common Resources | Source
