= Use Case - Customer Onboarding - Banking

Customer onboarding with loan origination creates an easy and straightforward onboarding experience. By empowering consumers to apply for a loan via a digital channel, review and accept the loan agreement, and then be added as a customer of the bank in seamless, regulatory-compliant steps.

Overview
Description
Solution overview
Objectives
Use case considerations
Technical consideratons and constraints
Business requirements
Solution design summary
High-level architecture
Sequence diagram
Systems involved
Client onboarding with loan origination
Goal
Main success scenario
Use case extension
See also
Downloadable assets
Description
This use case leverages a generic Core Banking system, with Salesforce Financial Services Cloud as the system of engagement and DocuSign as the document management system. The APIs and templates enable you to accelerate time to value. Use the assets as they are, or extend them to suit the needs of your own organization.

Glossary
Term	Definition
CIM	The Cloud Information Model defines a set of standard data structures that can be used as canonical representations of common entities for integrating systems.
FINS	Abbreviated term referring to the Financial and Insurance industries, consisting of the Banking, Insurance, and Wealth Management domains.
MDM	A Master Data Management (MDM) solution provides an accurate, consistent and complete copy of master data for use by enterprise applications and business partners. Most solutions include data quality tools and workflow processes for managing conflicting updates.
Solution overview
The primary use case for this solution is to onboard a new client through a loan application process. The creation of the initial marketing campaign described by the functional use case document is outside the scope of this solution.

Before you begin
bulb.png	The Accelerators setup guide provides general information on getting started with the accelerator components. This includes instructions on setting up your local workstation for configuring and deploying the applications.
Objectives
Support the receipt and processing of a new loan application
Support the submission of loan documents and receipt of electronic signatures
Create a new customer and loan account in the target financial system
Provide a means for customers to view their customer and loan account details
Use case considerations
Must support loan application submission and processing workflow
Must support customer and account synchronization to a system of record
Must support the generation of loan agreement documents and capture receipt of signatures from individuals
Technical considerations and constraints
The following lists the technical considerations for this solution design:

Use CIM as the canonical model, where applicable (e.g., for Customers)
The canonical model for banking accounts will include loan applications
The following applications will be leveraged for this solution: Core Banking System (generic), Salesforce Financial Services Cloud (FSC), Loan Origination System (generic), DocuSign, and MDM (generic)
The following lists the technical constraints for this solution design:

The Core Banking system is simulated using a generic database
A Loan Origination System (LOS) sandbox environment is simulated using a generic database
The generic Credit Bureau System API returns a random credit score
Business requirements
The following summarizes the business requirements as it pertains to the solution design:

The loan application submission will be captured via the Mobile interface and recorded in a generic Loan Origination System (LOS)
The personal information given on the application will be used to create/update an Individual entry in both FSC and MDM
A loan agreement document will be generated based on the content of the loan application and associated with the application in the LOS
The agreement document must be submitted to DocuSign in order to obtain the individual's signature, indicating that they agree to the terms and conditions
Upon receiving confirmation that the document has been signed, a Customer must be created or updated in FSC and a new Loan Account created for them
Solution design summary
The implementation of this use case builds upon the Core banking foundation use case and adds the following capabilities:

Full customer sync between Core Banking, FSC, and the FINS DB (customer profile data store)
A generic Loan Origination System, using the FINS DB for data storage
Integration with DocuSign, both for submitting documents and receiving events
Additional endpoints for the Mobile Experience API to support the retrieval and submission of loan applications
For the customer sync process, existing assets from the Retail accelerator are leveraged. These are customized and deployed separately. To support testing and demo activities, the Mobile Experience API provides a method to obtain a loan application form, which can be filled out and submitted to begin the process. For this release, a random credit score is calculated and the approve/deny decision is made based upon a configurable score threshold.

High-level architecture
The following diagram represents the entire solution, including the Core banking foundation and Customer onboarding - banking use cases:

fins-customeronboarding-architecture.png
Sequence diagram
The following diagram illustrates the processing sequence for this use case:

fins-customeronboarding-sequence.png
Systems involved
Core Banking System (generic)
DocuSign
Loan Origination System (generic)
MDM (generic)
Salesforce Financial Services Cloud (FSC)
back to top

Client onboarding with loan origination
Goal
Receive a new loan application
Process the loan application through to final acceptance (signed document)
Create a new customer and loan account for servicing
Main success scenario
Customer submits a new loan application via their mobile device
The Individual information is captured in Core Banking, FSC, and MDM
Loan application is processed according to a predefined workflow
An agreement document is generated and sent to the client for signature
Upon acceptance (document signed), a new customer is created in Core Banking, FSC, and MDM
A new loan account is created in Core Banking, FSC, and MDM
Use case extension
Terms are rejected by the customer
Loan application is marked as rejected, no customer or account created
Downloadable assets
FINS System APIs

Core Banking Accounts System API | API Specification | Implementation Template
Core Banking Customers System API | API Specification | Implementation Template
Credit Bureau System API | API Specification | Implementation Template
DocuSign System API | API Specification | Implementation Template
Loan Origination System API | API Specification | Implementation Template
MDM Accounts System API | API Specification | Implementation Template
MDM Customers System API | API Specification | Implementation Template
Salesforce Customers System API | API Specification | Implementation Template
Salesforce Financial System API | API Specification | Implementation Template
FINS Process APIs

Bank Accounts Process API | API Specification | Implementation Template
Bank Loans Process API | API Specification | Implementation Template
Core Banking Poller Process API | API Specification | Implementation Template
Customers Process API | API Specification | Implementation Template
FINS Experience APIs

DocuSign Experience API | API Specification | Implementation Template
Mobile Experience API | API Specification | Implementation Template
Salesforce Financial Experience API | API Specification | Implementation Template
FINS Listeners

Salesforce Topic Listener | Implementation Template
Custom components

FINS Banking Library | Source
FINS Common Resources | Source
FINS Financial Account Sync Lightning Web Component | Source
ID Graph Lightning Web Component | Source
