= SAP Custom BAPI Setup Guide - Customer Profile Sync

The following provides guidance on how to use the custom BAPI code (e.g., ZBAPI_CUSTOMER_V3) for your SAP instance.

Important: You must complete the following instructions before proceeding to Use case 1 - Customer profile sync from SAP.

BAPI custom objects
You must create the following ABAP objects in order to use this custom BAPI, which are described below.

Data elements
Z_MASTER_ID
Structures
ZSTR_PERSON
ZSTR_ORGANIZATION
ZSTR_GROUP
ZES_CUSTOMER
ZES_CONTROLDATA
Table types
ZTY_CUSTOMER
Transparent tables
ZTT_CUSTOMER
Function groups
ZFG_CUSTOMER
ZFG_CUSTOMER2
Function modules
ZBAPI_CUSTOMER modules

ZBAPI_CUSTOMER
ZBAPI_CUSTOMER_CREATE
ZBAPI_CUSTOMER_CUSTOM_FIELDS
ZBAPI_CUSTOMER_UPDATE
More ZBAPI modules

ZBAPI_QUERY
ZBAPI_ADDR_QUERY
ZBAPI_QUERY_SAP
ZBAPI_CUST_QUERY
ZBAPI_CUSTOMER_CD
Creating data elements
Object	How to create
Z_MASTER_ID	sfc-retail-com-bapi_01.png
Creating structures
Object	How to create
ZSTR_PERSON	retail-2.2-bapi-01.1.png
ZSTR_ORGANIZATION	retail-2.2-bapi-01.2.png
ZSTR_GROUP	retail-2.2-bapi-01.3.png
ZES_CUSTOMER	retail-2.2-bapi-01.4.png
ZES_CONTROLDATA	retail-2.2-bapi-01.5.png
Creating table types
Object	How to create
ZTY_CUSTOMER	sfc-retail-com-bapi_05.png
Creating transparent tables
Object	How to create
ZTT_CUSTOMER	retail-2.2-bapi-05.1.png


back to top

Creating function groups and function modules
ZBAPI Customer modules
Create the function group "ZFG_CUSTOMER_V3".

Create the function module "ZBAPI_CUSTOMER_V3", using "Remote-enable module" as processing type:

sfc-retail-com-bapi_06.png

Complete the import parameters with the following:

sfc-retail-com-bapi_07.png

Complete the export parameters with the following:

sfc-retail-com-bapi_08.png

Copy and paste the code from "ZBAPI_CUSTOMER_V3.txt".

Create the function module "ZBAPI_CUSTOMER_CREATE_V3":

sfc-retail-com-bapi_09.png

Complete the import parameters with the following:

retail-2.2-bapi-09.1.png

Complete the export parameters with the following:

sfc-retail-com-bapi_11.png

Copy and paste the code from "ZBAPI_CUSTOMER_CREATE_V3.txt".

Create the function module "ZBAPI_CUSTOMER_CUSTOM_FLDS_V3":

sfc-retail-com-bapi_15.png

Complete the import parameters with the following:

retail-2.2-bapi-15.1.png

Copy and paste the code from "ZBAPI_CUSTOMER_CUSTOM_FIELDS_V3.txt".

Create the function module "ZBAPI_CUSTOMER_UPDATE_V3":

sfc-retail-com-bapi_12.png

Complete the import parameters with the following:

retail-2.2-bapi-12.1.png

Complete the export parameters with the following:

retail-2.2-bapi-12.2.png

Copy and paste the code from "ZBAPI_CUSTOMER_UPDATE_V3.txt".

Create the function module "ZBAPI_QUERY_V3", using "Remote-enable module" as processing type:

sfc-retail-com-bapi_36.png

Complete the import parameters with the following:

retail-2.2-bapi-36.1.png

Complete the export parameters with the following:

sfc-retail-com-bapi_22.png

Copy and paste the code from "ZBAPI_QUERY_V3.txt".

Create the function module "ZBAPI_CONTROL_DATA_V3":

sfc-retail-com-bapi_21.png

Complete the import parameters with the following:

sfc-retail-com-bapi_24.png

Complete the export parameters with the following:

sfc-retail-com-bapi_19.png

Copy the source code from "ZBAPI_CONTROL_DATA_V3.txt".

Activate the entire function group by right-clicking on it in the tree and then selecting "Activate":

sfc-retail-com-bapi_35.png

Create the function group "ZFG_CUSTOMER2".

Create the function module "ZBAPI_ADDR_QUERY", using "Remote-enable module" as processing type:

sfc-retail-com-bapi_17.png

Complete the import parameters with the following:

sfc-retail-com-bapi_20.png

Complete the export parameters with the following:

sfc-retail-com-bapi_22.png

Copy and paste the code from "ZBAPI_ADDR_QUERY.txt".

Create the function module "ZBAPI_CONTROL_DATA" using the import parameters as follows:

retail-2.2-bapi-22.1.png

Use the export parameters as in the following:

retail-2.2-bapi-22.2.png

Copy the source code from "ZBAPI_CONTROL_DATA.txt".

Activate the entire function group by right-clicking on it in the tree and selecting 'Activate':

retail-2.2-bapi-22.3.png

Complete the following:
Create a customer group ZSME (Logistics - General->Business Partner->Customer->Control->Define and Assign Customer Number Ranges)
Create a partner group ZSME (Cross-Application Components->SAP Business Partner->Business Partner->Basic Settings->Number Ranges and Settings) from the transaction SPRO
Synchronize them from the same transaction (Cross-Application Components->Master Data Synchronization->Customer/Vendor Integration->Business Partner Settings->Settings for Customer Integration->Assign Keys->Define Number Assignment for Direction BP to Customer)

retail-2.2-bapi-22.4.png


back to top

More ZBAPI modules
The following describes how to sufficiently set up your SAP instance in order to use the following custom BAPIs:

ZBAPI_ADDR_QUERY
ZBAPI_QUERY_SAP
ZBAPI_CUST_QUERY
ZBAPI_CUSTOMER_CD
To create ABAP custom objects, groups, and modules:

Create the same dictionary objects created for the BAPI ZBAPI_CUSTOMER using the following structure/table type:

retail-2.2-bapi-51.png

retail-2.2-bapi-52.png

Create the function group ZFG_CUSTOMER2.

Create the function module ZBAPI_ADDR_QUERY using 'Remote-enable module' as the processing type:

retail-2.2-bapi-53.png

Complete the import parameters with the following:

retail-2.2-bapi-54.png

Complete the export parameters with the following:

retail-2.2-bapi-55.png

Copy and paste the code from 'ZBAPI_ADDR_QUERY.txt'.

Create the function module ZBAPI_ADDR_SAP using 'Remote-enable module' as the processing type:

retail-2.2-bapi-56.png

Complete the import parameters with the following:

retail-2.2-bapi-57.png

Complete the export parameters with the following:

retail-2.2-bapi-58.png

Copy and paste the code from 'ZBAPI_QUERY_SAP.txt'.

Create the function module ZBAPI_CUST_QUERY using 'Remote-enable module' as the processing type:

retail-2.2-bapi-59.png

Complete the import parameters with the following:

retail-2.2-bapi-60.png

Complete the export parameters with the following:

retail-2.2-bapi-61.png

Copy and paste the code from 'ZBAPI_CUST_QUERY.txt'.

Create the function module ZBAPI_CUSTOMER_CD using 'Remote-enable module' as the processing type:

retail-2.2-bapi-62.png

Complete the import parameters with the following:

retail-2.2-bapi-63.png

Complete the export parameters with the following:

retail-2.2-bapi-64.png

Copy and paste the code from 'ZBAPI_CUSTOMER_CD.txt'.

Activate the entire function group by right-clicking on it in the tree and selecting 'Activate':

retail-2.2-bapi-65.png
