= Object Mappings

== Customer Profile Sync

=== Source-type mappings

The following table summarizes how representations of a customer or individual from each system will be mapped to CIM types:

[%header%autowidth.spread]
|===
| Source System | Source Type | CIM Types | Mapping Notes

| Salesforce
Service Cloud | Person Accounts | Individual

CustomerContactAddress

Contact Email

Contact Phone | Person Account is represented as record type, mapping to Account and Contact

| SAP | Customer | IndividualCustomer

Contact Address

Contact Email

Contact Phone |
|===

=== Target-type mappings

The following table summarizes how representations of a customer or individual from each system will be mapped from CIM types:

[%header%autowidth.spread]
|===
| Target System | CIM Type | Target Types | Mapping Notes

| Salesforce
Service Cloud | CustomerIndividual

Contact Address

Contact Email

Contact Phone | PersonAccounts | Relevant fields only

| SAP | CustomerIndividual

Contact Address

Contact Email

Contact Phone | Customer | Relevant fields only
|===


== See Also 

* xref:prerequisites.adoc[Prerequisites]
* xref:index.adoc[MuleSoft Accelerator for Service Cloud]
