= Salesforce Customization Guide

This guide provides instruction on Salesforce customization that are required to enable the customer 360, product and sales order sync use cases to function end-to-end.

== Custom Object

The following object must be created either manually or via Apex script as per the instructions provided below.

|===
| Salesforce Object Name | Singular Label | Plural Label

|Managed_External_Id
|Managed External Identifier
|Managed External Identifiers
|===

=== Create Custom Object Manually

1. In your Salesforce org, click Setup, and then select Setup to open Setup.
2. Click the Object Manager tab. If you don’t see it, enter Object Manager in the Quick Find box.
3. On the Object Manager page, click Create | Custom Object.
4. For Label, enter the value in `Singular Label`.
5. For Plural Label, enter the value in `Plural Label`.
6. For Object Name, enter the value in `Salesforce Object Name`.
7. Leave the rest of the values as default and click Save.

=== Create Custom Object via Apex Script

An Apex class called `CustomObjectUtility` and `MetadataService` are used to create a custom object programmatically. The source can be found on https://anypoint.mulesoft.com/exchange/2cc3c2c9-ddd3-4582-bdcc-b510f30065a7/rcg-common-resources/[RCG Common Resources] project and https://github.com/financialforcedev/apex-mdapi/blob/master/apex-mdapi/src/classes/MetadataService.cls[MetadataService] respectively. Download the project and follow the steps below.

1. Click on the Salesforce Setup icon and select `Developer Console` to open a new console window.
1. Go to `File > New > Apex class` and create a new class named `CustomObjectUtility`.
1. Copy the code from `rcg-common-resources/salesforce/CustomObjectUtility.apxc` to the script editor.
1. Select the `Save` from the File menu option to compile and save the class.
1. Go to `File > New > Apex class` and create a new class named `MetadataService`.
1. Copy the code from `https://github.com/financialforcedev/apex-mdapi/blob/master/apex-mdapi/src/classes/MetadataService.cls` to the script editor.
1. Select the `Save` from the File menu option to compile and save the class.
1. Select `Debug > Open Execute Anonymous Window`.
1. Copy and paste the contents of `rcg-common-resources/salesforce/CreateCustomObjects.txt` into the window.
1. Enable the `Open Log` option, and then click the *Execute* button.

Once the script completes, select the `Debug Only` filter option to show only the results of each create request. Verify that custom object has been created successfully.

== Custom Fields

The following fields must be created in the corresponding objects either manually or via Apex script as per the instructions provided below.

[%header%autowidth.spread]
|===
| Salesforce Object Label | Field Label | Field Name | Data Type | Length | Unique | ExternalId | Formula

| Account
| Global Billing Address ID
| Global_BillingAddress_Id
| Text
| 36
| Y
| Y
| -

| Account
| Global Customer ID
| Global_Customer_Id
| Text
| 36
| Y
| Y
| -

| Account
| Global Email Address ID
| Global_EmailAddress_Id
| Text
| 36
| Y
| Y
| -

| Account
| Global Fax Number ID
| Global_FaxNumber_Id
| Text
| 36
| Y
| Y
| -

| Account
| Global Mailing Address ID
| Global_MailingAddress_Id
| Text
| 36
| Y
| Y
| -

| Account
| Global Mobile Number ID
| Global_MobileNumber_Id
| Text
| 36
| Y
| Y
| -

| Account
| Global Party ID
| Global_Party_Id
| Text
| 36
| Y
| Y
| -

| Account
| Global Phone Number ID
| Global_PhoneNumber_Id
| Text
| 36
| Y
| Y
| -

| Account
| Global Shipping Address ID
| Global_ShippingAddress_Id
| Text
| 36
| Y
| Y

| Account
| Customer Status
| Customer_Status
| Picklist
| -
| N
| N
| -

| Managed External Identifier
| External Id
| External_Id
| Text
| 80
| N
| N
| -

| Managed External Identifier
| External Id Type
| External_Id_Type
| Picklist
| -
| N
| N
| -

| Managed External Identifier
| Object Id
| Object_Id
| Text
| 80
| N
| N
| -

| Managed External Identifier
| Object Type
| Object_Type
| Picklist
| -
| N
| N
| -

| Managed External Identifier
| Status
| Status
| Picklist
| -
| N
| N
| -

| Managed External Identifier
| Status Last Changed
| Status_Last_Changed
| Date/Time
| -
| N
| N
| -

| Order
| Global_SalesOrder_Id
| Global_SalesOrder_Id
| Text
| 36
| Y
| Y
| -

| Order
| Total Tax
| Total_Tax__c
| Currency
| -
| -
| -
| -

| Order
| Shipping
| Shipping__c
| Currency
| -
| -
| -
| -

| Order
| Order Total Amount
| OrderTotalAmount__c
| Formula (Currency)
| -
| -
| -
| Shipping__c + Total_Tax__c + TotalAmount

| Product
| Global_Product_Id
| Global_Product_Id
| Text
| 36
| Y
| Y
| -

| Product
| Product Group
| Product_Catalog__c
| Picklist
| -
| N
| N
| -

| Product
| Short Description
| Short_Description__c
| Text
| 255
| N 
| N
| -

| Product
| Item Short Description
| Item_Short_Description__c
| Text
| 255
| N 
| N
| -

| Product
| Item Long Description
| Item_Long_Description__c
| Text
| 255
| N 
| N
| -

| Product
| Status
| Status__c
| Picklist
| -
| N
| N
| -

|===

[NOTE]
Unique fields should be case-sensitive.

=== Create via Apex Script

An Apex class called `CustomFieldUtility` is used to create custom fields programmatically. The source for this class can be found in the https://anypoint.mulesoft.com/exchange/2cc3c2c9-ddd3-4582-bdcc-b510f30065a7/rcg-common-resources/[RCG Common Resources] project. Download this project and follow the steps below.

. Click on the Salesforce Setup icon and select `Developer Console` to open a new console window.
. Go to `File > New > Apex class` and create a new class named `CustomFieldUtility`.
. Copy the code from `rcg-common-resources/salesforce/CustomFieldUtility.apxc` to the script editor.
. Select the `File > Save` menu option to compile and save the class.
. Select `Debug > Open Execute Anonymous Window`.
. Copy and paste the contents of `rcg-common-resources/salesforce/CreateCustomFields.txt` into the window.
. Enable the `Open Log` option and click the *Execute* button.

Once the script completes, select the `Debug Only` filter option to show just the results of each create request. Verify that all fields have been successfully created.

=== Create Manually via Salesforce

To create each of these custom fields and enable visibility for them on page layouts:

. Click on the Salesforce Setup icon.
. Select the `Object Manager` tab from the Setup home page.
. Find and select the target Salesforce object.
. Select the `Fields & Relationships` page.
. Click the *New* button and create the field as specified above.
. Once the field has been created, click the `Set Field-Level Security` button (or do these steps later - see below).
. Enable for desired profile, or tick the checkbox next to `Visible` to enable visibility for the desired profile(s).

Repeat these steps for each custom field in the above table.

[NOTE]
1. Instead of adjusting permissions for each field as you go, if you are only making them available to one or two profiles, then it may be more efficient to go to `Users > Profiles > {profile} > Object Settings` for each object and adjust the permissions for multiple fields at once.
1. All `Global_*_Id__c` fields should be visible in layouts (as described above) but made *read-only* to avoid issues with data synchronization.

== Fields to Be Updated

The picklist fields mentioned in the table needs to be updated as per the instructions provided below.

[%header%autowidth.spread]
|===
| Salesforce Object Label | Field Label | Field Name | Data Type | To be updated values
| Order | Order Type | Type | Picklist | ADD_ON, CANCELLATION, INITIAL, JOURNAL, RENEWAL, RETURN, SUBSCRIPTION, UPGRADE
| Order | Status | Status | Picklist | CANCELLED, CREATED, CONFIRMED, DELIVERED, IN_CART, IN_TRANSIT, INVOICED, LOST, PARTIALLY_SHIPPED, PICKUP_AVAILABLE, PROCESSING, REJECTED, RETURNED
|===

To update picklist values for a field in the specified object:

. Click on the Salesforce Setup icon.
. Select the `Object Manager` tab from the Setup home page.
. Find and select the target Salesforce object.
. Select the `Fields & Relationships` page.
. Search for the target field with field label and select it.
. Under the header `Picklist Values`, select `New`.
. Add the respective `To be updated values` from the table with each picklist value on its own line.
. Click `Save`.

Repeat these steps for each field in the above table.

If the fields under `Custom Fields` header were created manually, update the picklist values for the fields in the table as per the instructions above.

[%header%autowidth.spread]
|===
| Salesforce Object Label | Field Label | Field Name | Data Type | To be updated values
| Account | Customer Status | Type | Picklist | Prospect, Onboarding, Active, Inactive, Closed, Deceased, Delinquent, Dormant
| Managed External Identifier | External Id Type | External_Id_Type__c | Picklist | SALESFORCE_B2C, SALESFORCE_CORE, PIM, OFBIZ, SAP_4HANA, MDM, SAP_ECC, SALESFORCE_MARKETING, POS, SALESFORCE_DC, SALESFORCE_LM, ORACLE_EBS
| Managed External Identifier | Object Type | Object_Type__c | Picklist | BillingAddress, Customer, Email, Fax, Household, Individual, MailingAddress, MobilePhone, Organization, Phone, Product, SalesOrder, ShippingAddress
| Managed External Identifier | Status | Status__c | VALID, INVALID
| Product | Product Group | Product_Catalog__c | Basic, Premium
| Product | Status | Status__c | VALID, INVALID
|===


== Configure Connected App for Authentication

Follow the below steps to generate the `Consumer Key` and `Consumer Secret` values required for Salesforce authentication.

. Click on the Salesforce Setup icon .
. Navigate to `Apps > App Manager`.
. Select `New Connected App`.
. Enter Connected App Name: `MuleSoft Accelerator`, API Name: `MuleSoft_Accelerator` and set your email address.
. In the `API (Enable OAuth Settings)` section, check the box `Enable OAuth Settings`.
. Set the callback URL `+http://localhost+`.
. From the `Selected OAuth Scopes` list, select `Full access (full)`.
. Click *Save* and then *Continue*.
. Click the *Manage* button to view details for the new connected app.
. Click the *Edit Policies* button.
. In the `OAuth Policies` section, for `Permitted Users` select `All users may self-authorize`.
. For `IP Relaxation`, select the `Relax IP restrictions` option.
. Click *Save*.

You now need to copy the `Consumer Key` and `Consumer Secret` values for use in configuring Mule application deployments. More specifically, these must be supplied as the values for the `sfdc.client-id` and `sfdc.client-secret` properties found in the `Clouhub-RCG-DEV` profile in your Maven `settings.xml` file.

. On the Setup Home page, navigate to `+Apps -> App Manager+`.
. Locate your new connected app and choose *View* from the actions dropdown for that item.
. In the *API (Enable OAuth Settings)* section, click the *Manage Consumer Details* button.
. Verify your identity by entering the verification code that was emailed to you.
. Copy the key and secret values and update your `settings.xml` file as described previously.

Download the https://anypoint.mulesoft.com/exchange/org.mule.examples/accelerator-common-resources-src[Accelerator Common Resources project^] for a sample `settings.xml` file that can be used as a starting point.

== Generating a Security Token for the Service Account

A token needs to be generated for the service account used by the Mule applications in order to connect to the Salesforce instance.

. Log in to Salesforce as the Service Account User, which is the account that will be used by the Mule applications to connect to Salesforce).
. Click the Username icon and select *Settings* from the menu.
. Select `My Personal Information > Reset My Security Token`. If you cannot find this, see the note at the end of these steps.
. Click *Reset Security Token*.
. Check the email inbox for an email from Salesforce with the new security token.

[NOTE]
If the option to reset your security token is not available, it is likely that one or more Login IP Ranges are in effect. These can be temporarily removed from the settings page of the profile assigned to the service account user.

== Create Platform Events and Apex Triggers

The following Platform Event Object and Apex Triggers must be created in order to capture updates from Salesforce. The scripts to create these Apex Triggers and add fields to Platform Event Object are located in the https://anypoint.mulesoft.com/exchange/2cc3c2c9-ddd3-4582-bdcc-b510f30065a7/rcg-common-resources/[RCG Common Resources] project.

|===
| Salesforce Object | Salesforce Platform Event Object | Salesforce Platform Event API Name | Apex Trigger Name

| Account
| Account
| Account__e
| AccountEventsPub
|===

=== Create Platform Event Object

This implementation requires `Platform Event` to be created in Salesforce. Follow these steps to create a `Platform Event` object:

. Log in to Salesforce.
. Click *Setup* and search for "Platform Events" in the *Quick Find* box. The Platform Events page shows with a list of available Platform Events.
. Click the *New Platform Event* button to create an Object. Complete the *Platform Information Details* fields, including *Label*, *Plural Label*, *Object with Salesforce Object*, and *Salesforce Platform Event API Name* as indicated in the previous table.
. Click *Save*.

. To add Custom Fields & RelationShips to Platform Event Definitions, run the utility script `CreatePlatformEventsCustomFields.txt` available in the `rcg-common-resources/salesforce` folder of https://anypoint.mulesoft.com/exchange/2cc3c2c9-ddd3-4582-bdcc-b510f30065a7/rcg-common-resources/[RCG Common Resources] project.
. Follow the steps to run the script provided in `Create via Apex Script` under `Custom Fields`.

=== Create Apex Triggers

Follow these steps to create the Apex Triggers:

. Log in to Salesforce.
. Click Setup to search for Object Manager in Quick Find Box.
. Search for the Salesforce object. This opens a page that shows the details of the object.
. Click *Triggers* in the Details section to view a list of available triggers for the object.
. Click *New*.
. Search for the Apex Trigger name, which is indicated in the previous table. Copy the Trigger Script code `CreateApexTriggers.txt` available in the `rcg-common-resources/salesforce` folder of https://anypoint.mulesoft.com/exchange/2cc3c2c9-ddd3-4582-bdcc-b510f30065a7/rcg-common-resources/[RCG Common Resources] project and paste it into the script editor.
. Obtain the `LastModifiedById` by running the query mentioned in the additional notes below.
. Replace the values in the script and save the trigger.
. Click *Save* and ensure the *isActive* checkbox is checked.

=== Additional Notes

* The Apex Trigger that is created filter records based on `LastModifiedBy <> {Service account ID}`. This is done to avoid cyclical updates performed by the Salesforce Customers System API. This can be obtained by running the query `SELECT Id FROM User WHERE Username='<service-account-username>'` in the Developer Console.

== See Also 

* xref:prerequisites.adoc[Prerequisites]
* xref:index.adoc[MuleSoft Accelerator for Retail]
