= Prerequisites for MuleSoft Accelerator for Healthcare

This page provides a summary of the guides available for configuring the various systems and products required to implement the use cases provided by this solution. The individual systems needed, and amount of configuration required, depend on which assets are to be deployed in your target environment(s) - refer to the use case pages for more details.

== Available Guides

The following setup and configuration guides are available for this accelerator:

<<<<<<< HEAD
* xref:sfdc-data-cloud-setup-guide.adoc[Salesforce Health Cloud Setup Guide]
* xref:sfdc-data-cloud-setup-guide.adoc[Salesforce Data Cloud Setup Guide]
=======
>>>>>>> 8c54069 (Completed initial migration of Consumer Goods)

Most of the implementation templates also contain details on requirements specific to those applications.

== See Also

<<<<<<< HEAD
* xref:accelerators-home::getting-started.adoc[Getting Started Guide]
=======
>>>>>>> 8c54069 (Completed initial migration of Consumer Goods)
* xref:index.adoc[MuleSoft Accelerator for Healthcare]
