= Release Notes
:mfg-version: 1.3

== v1.2

6 September 2022

=== Total Productive Maintenance Use Case

This release introduces the https://anypoint.mulesoft.com/exchange/0b4cad67-8f23-4ffe-a87f-ffd10a1f6873/mulesoft-accelerator-for-manufacturing/minor/{mfg-version}/pages/Use%20case%203%20-%20Total%20productive%20maintenance/[Total productive maintenance^] use case, which helps manufacturers to maintain factory floor equipments.

== v1.1

8 June 2022

=== Sales Rebate Management Use Case

This release introduces the https://anypoint.mulesoft.com/exchange/0b4cad67-8f23-4ffe-a87f-ffd10a1f6873/mulesoft-accelerator-for-manufacturing/minor/{mfg-version}/pages/Use%20case%202%20-%20Sales%20rebate%20management/[Sales rebate management^] use case, which helps manufacturers to seamlessly manage sales rebate programs.

This release also includes the following enhancements:

* customers can be synced bidirectionally between SAP S/4 HANA and Salesforce Manufacturing Cloud.

== v1.0

28 March 2022

=== Initial Release

This is the first release of the MuleSoft Accelerator for Manufacturing.

<<<<<<< HEAD
This release introduces the https://anypoint.mulesoft.com/exchange/0b4cad67-8f23-4ffe-a87f-ffd10a1f6873/mulesoft-accelerator-for-manufacturing/minor/{mfg-version}/pages/Use%20case%201%20-%20Run-rate%20business%20management/[Run-rate business management^] use case, which helps streamline sales agreements and account forecasts in Salesforce Manufacturing Cloud.
=======
<<<<<<<< HEAD:modules/ROOT/pages/mfg/mfg-release-notes.adoc
This release introduces the https://anypoint.mulesoft.com/exchange/0b4cad67-8f23-4ffe-a87f-ffd10a1f6873/mulesoft-accelerator-for-manufacturing/minor/{mfg-version}/pages/Use%20case%201%20-%20Run-rate%20business%20management/[Run-rate business management^] use case, which helps streamline sales agreements and account forecasts in Salesforce Manufacturing Cloud.
========
This release introduces the Run-rate business management use case, which helps streamline sales agreements and account forecasts in Salesforce Manufacturing Cloud.
>>>>>>>> e45997f (Update index.adoc):manufacturing/1.3/modules/ROOT/pages/release-notes.adoc
>>>>>>> e45997f (Update index.adoc)

== See Also

* xref:index.adoc[MuleSoft Accelerator for Manufacturing]
