= Anypoint MQ Setup Guide

The Postman collection `Anypoint-MQ-Configuration` can be used to
pre-create all Anypoint MQ destinations required by the accelerator
components. This collection can be found in the
https://anypoint.mulesoft.com/exchange/997d5e99-287f-4f68-bc95-ed435d7c5797/accel-b2b-common-resources-src/[Accelerator
B2B Common Resources] project

== Environment Settings

The collection requires the `dev` environment to be created and assigned
proper values reflecting your target Anypoint org before running any of
the requests. A template for this environment, which can be imported
directly into your Postman workspace, has also been provided in the
https://anypoint.mulesoft.com/exchange/997d5e99-287f-4f68-bc95-ed435d7c5797/accel-b2b-common-resources-src/[Accelerator
B2B Common Resources] project.

== Running the Collection

The collection itself defines variables that must be overridden prior to
running any requests. The contents of the collection have been organized
into separate folders, which should be executed in the following order:

. Authorization
. Client-Management (optional)
. Queue-Management
. Exchange-Management

Requests in the `Verification` folder can be run to validate the results
of the above operations. If desired, objects created by the collection
can be cleaned up by running requests found in the `Deletions` folder.

== Verify Destinations

The following MQ destinations will be created on successful execution.

|===
| Queue Name| Bound to Exchange| Dead Letter Queue Name

| accel-b2b-orders-update-queue
| accel-oms-update-exchange
| accel-b2b-orders-update-dl-queue 

| accel-oms-exception-queue
| 
| 
|===

== See Also

* xref:prerequisites.adoc[Prerequisites]
* xref:index.adoc[MuleSoft Accelerator for OMS]
