== Overview

The MuleSoft Accelerator for Life Sciences helps pharmaceuticals, medical device companies, and contract research organizations (CROs) integrate digital operations and get their products to market faster. Our foundational assets are expertly designed to jumpstart your top integration and business initiatives so that IT teams can spend more time innovating and less time building from scratch.

== Use cases

The following describes how to use the MuleSoft Accelerator for Life Sciences assets:

* https://anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-life-sciences/minor/1.1/draft/pages/Use%20case%201%20-%20Clinical%20trial%20analytics/[Use case 1: Clinical trial analytics^] - Run more intelligent, data-driven trials with pre-built assets that surface relevant study and stakeholder information from Veeva. Easily consolidate this information into data lakes for analysis in business intelligence platforms like Tableau.
* https://anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-life-sciences/minor/1.1/pages/Use%20case%202%20-%20Site%20payment%20modernization/[Use case 2: Site payment modernization^] - Streamline the clinical trial site payment process by integrating relevant study data from CTMS systems, like Veeva, to generate and transmit payments to sites.

== Other related solutions

For solutions related to healthcare, the https://anypoint.mulesoft.com/exchange/org.mule.examples/catalyst-accelerator-for-healthcare[Accelerator for Healthcare^] helps organizations enable interoperability, simplify EHR connectivity, and power Patient 360 initiatives.

== What is a MuleSoft Accelerator?

https://anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerators-introduction/[Accelerators^] are a collection of technical assets (predominantly API specifications and implementation templates) and documentation to accelerate the implementation of multiple use cases supporting a larger business or industry problem.

Accelerators are designed as modular building blocks. Customers can change the patterns, mappings, and endpoints to suit their needs. The accelerators represent best practices recommended to customers to accomplish these use cases. Customers can save hours of discovery, design, development, and testing each time they use an accelerator asset.

To access any of the links described in this Accelerator, you must log into https://anypoint.mulesoft.com/login/[Anypoint Platform^].

'''

=== Feedback

Give the assets a try and if you have any questions or feedback, please let us know at link:mailto:solutions-questions@mulesoft.com[solutions-questions@mulesoft.com]. You can also engage with other users on the MuleSoft Forum, and submit ideas in the Ideas Portal. We look forward to hearing from you!

== See Also

* xref:accelerators-home::getting-started.adoc[Getting Started Guide]
* xref:release-notes.adoc[Release Notes] for this accelerator
