= Anypoint MQ Setup Guide

The Postman collection `Anypoint-MQ-Configuration` can be used to create all Anypoint MQ destinations required by the accelerator components. This collection can be found in the https://anypoint.mulesoft.com/exchange/997d5e99-287f-4f68-bc95-ed435d7c5797/accel-b2b-common-resources-src/[Accelerator B2B Common Resources] project.

== Environment Settings

Create the `dev` environment by using the template in the https://anypoint.mulesoft.com/exchange/997d5e99-287f-4f68-bc95-ed435d7c5797/accel-b2b-common-resources-src/[Accelerator B2B Common Resources] project and importing it into your Postman workspace. Assign the values that reflect your target Anypoint Platform org before running the requests.

== Running the Collection

The collection defines the variables that you must override prior to running any requests. The collection is organized into separate folders, which should be executed in the following order:

. Authorization
. Client-Management (optional)
. Queue-Management
. Exchange-Management

Requests in the `Verification` folder can be run to validate the results of the above operations. If desired, objects created by the collection can be cleaned up by running requests found in the `Deletions` folder.

== Verify Destinations

The following MQ destinations will be created on successful execution.

|===
| Queue Name| Bound to Exchange| Dead Letter Queue Name

| accel-b2b-orders-update-queue
| accel-oms-update-exchange
| accel-b2b-orders-update-dl-queue 

| accel-oms-exception-queue
| -
| -
|===

== See Also

* xref:prerequisites.adoc[Prerequisites]
* xref:index.adoc[MuleSoft Accelerator for Salesforce OMS]
