= MuleSoft Accelerator for Salesforce OMS
:salesforce-oms-version: {page-component-version}
:page-aliases: 1.0@retail::oms-assets.adoc

MuleSoft Accelerator for Salesforce OMS enables you to integrate your Order Management System (OMS) with external business partners and application ecosystems by leveraging the application and B2B integration capabilities of Anypoint Platform. The solution accelerates the implementation of Electronic Data Interchange (EDI) messaging and other integrations into Salesforce OMS.

== Use Case

=== B2B EDI Order Lifecycle Automation

The https://anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-salesforce-oms/minor/{salesforce-oms-version}/pages/7ij-1pd/B2B%20EDI%20Order%20Lifecycle%20Automation/[B2B EDI Order Lifecycle Automation] use case lets you add EDI as a direct order intake channel to manage and service EDI orders across the full order management lifecycle. 

== See Also 

* xref:accelerators-home::getting-started.adoc[Getting Started]
* xref:prerequisites.adoc[Prerequisites]
* xref:release-notes::accelerators/salesforce-oms/salesforce-oms-release-notes.adoc[Release Notes]
* https://anypoint.mulesoft.com/exchange/org.mule.examples/mulesoft-accelerator-for-salesforce-oms/[MuleSoft Accelerator for Salesforce OMS on Exchange]