= Prerequisites for MuleSoft Accelerator for OMS
:salesforce-oms-version: {page-component-version}

This page summarizes the guides available for configuring the systems and products that are needed to implement the use case provided by this solution. The individual systems and the amount of configuration required depends on which assets you're deploying in your target environment. See the https://anypoint.mulesoft.com/exchange/0b4cad67-8f23-4ffe-a87f-ffd10a1f6873/mulesoft-accelerator-for-salesforce-oms/minor/{salesforce-oms-version}/pages/B2B%20EDI%20Order%20Lifecycle%20Automation/[B2B EDI Order Lifecycle Automation] use case for the list of downloadable assets.

== Available Guides

The following setup guides are available for this accelerator:

* xref:anypointmq-setup-guide.adoc[Anypoint MQ Setup]
* xref:sfdc-oms-setup-customization-guide.adoc[Salesforce OMS Setup and Customization]
* xref:anypoint-partner-manager-setup-guide.adoc[Anypoint Partner Manager Setup]

The implementation templates also contain details on the requirements specific to those applications.

== See Also

* xref:accelerators-home::getting-started.adoc[Getting Started]
* xref:index.adoc[MuleSoft Accelerator for Salesforce OMS]
