= Getting Started with MuleSoft Accelerators

This guide helps you configure your local build environment to download, modify, and deploy accelerator assets successfully.

== Quick Start

To get started:

. Set up your xref:build-environment.adoc[local build environment] with the required software and Maven build configuration.
. Download and configure the assets required for the use case(s) you wish to implement. Some use cases will require changes to the systems being integrated (for example, SAP, Salesforce Service Cloud, etc.) Be sure to read and follow the instructions specified for each accelerator carefully. This also applies when using only a few select assets instead of implementing complete use cases.
. Deploy the applications individually to your own CloudHub instance, either manually or by using simple Maven commands. There may also be some helper configuration files available for deploying multiple components at once.

Refer to the sections below for more details on obtaining and using accelerator assets.

=== Asset Types

The following table provides more information about the types of accelerator assets provided and how they fit into the overall solution.

[%header%autowidth.spread]
|===
|Type	|Purpose	|Example
|API Spec Fragments	|Shared RAML specifications reused by multiple APIs. These define standard characteristics, data types and response codes common across most APIs.	|Accelerator Global Resources
|REST APIs	|RAML specifications describing the resources and methods an API makes available to consumers. They are categorized into layers - System, Process, Experience - as per MuleSoft's API-led approach.	|Accelerator OMS System API
|Templates	|Runtime implementations of individual APIs and other integrations. These must be customized and deployed to your own Mule runtime environment (for example, CloudHub) to implement desired use cases.	|Accelerator OMS System API - Implementation Template
|Custom	assets |Documentation and other downloadable components that do not fit into other categories.	|Accelerator POM Parent - Source
|===

=== Obtaining Accelerator Assets

All accelerator assets are available from the main Anypoint Exchange site and are freely downloadable by customers with current subscriptions. Refer to the sections in the page navigation menu on the left for more information about configuring, building, and deploying these assets.

The following instructions assume you have already configured your Maven `settings.xml` file according to the xref:build-environment.adoc[build environment configuration] guide.

==== Import Directly from Anypoint Studio or Import from Anypoint Code Builder

All accelerator templates can be imported into Anypoint Studio directly from Exchange if your Anypoint credentials have been provided; refer to the Studio documentation for more details.

* From Studio, open the Exchange window (typically the second toolbar button from the left).
* If prompted, log in to Anypoint Exchange.
* Select the `Provided by MuleSoft` view (top-left).
* Click the *Asset type* selector to the left of the *Search* field and choose *Templates*.
* Copy and paste the title of this API into the *Search* field and press *Enter* on your keyboard.
* Click on the desired result to open the home page for the asset.
* Click on the *Open* icon (top-right) to import the asset into the current workspace.

If it appears, you can safely cancel out of the `Update your Workspace` dialog as well as the subsequent `Are you sure?` prompt: our templates will work correctly with or without the suggested changes.

To import from Anypoint Code Builder, visit xref:code-builder::int-import-mule-project.adoc[Importing Projects into the IDE].

==== Download and Import Manually to Anypoint Studio

The following instructions assume you are viewing this page from your browser:

* Click the *Download* button (top-right) and save the template archive to your local file system.
* In Studio, ensure the current perspective is set to `Mule Design`.
* Right-click in an empty area in the `Package Explorer` and select *+Import...+*.
* In the select dialog, expand the *Anypoint Studio* folder.
* Choose the `Packaged mule application (.jar)` option and click *Next >*.
* Enter the full path name of the downloaded jar file or select from the file browser.
* Remove the version and `mule-application-template` suffixes from the project name, if desired.
* Click *Finish* to import the project.

As above, you can safely cancel out of the `Update your Workspace` dialog, if prompted.

=== Next Steps

Ensure your xref:build-environment.adoc[Build Environment] is configured correctly before attempting to import or deploy any assets. Also refer to the xref:application-deployment.adoc[Application Deployment], xref:application-testing.adoc[Application Testing] and xref:additional-customizations.adoc[Additional Customizations] pages for more details on deploying, testing, and customizing accelerator assets. For more information about accelerators, see xref:index.adoc[MuleSoft Accelerators].

== See Also

* xref:build-environment.adoc[Build environment]
* xref:application-deployment.adoc[Application deployment]
* xref:application-testing.adoc[Application testing]
* xref:additional-customizations.adoc[Additional customizations]
* xref:index.adoc[MuleSoft Accelerators]
